services:
  - type: web
    name: news-analyzer-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements-render-lite.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: NEWSAPI_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "False"
      - key: CORS_ORIGINS
        value: "https://news-analyzer-frontend.onrender.com"
      - key: PYTORCH_CUDA_ALLOC_CONF
        value: "max_split_size_mb:128"
      - key: OMP_NUM_THREADS
        value: "1"
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    rootDir: backend
