services:
  - type: web
    name: news-analyzer-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements-render.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: NEWSAPI_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "False"
      - key: CORS_ORIGINS
        value: "https://news-analyzer-frontend.onrender.com"
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    rootDir: backend
